Document: ncrack
Title: Debian ncrack Manual
Author: <insert document author here>
Abstract: This manual describes what ncrack is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ncrack/ncrack.sgml.gz

Format: postscript
Files: /usr/share/doc/ncrack/ncrack.ps.gz

Format: text
Files: /usr/share/doc/ncrack/ncrack.text.gz

Format: HTML
Index: /usr/share/doc/ncrack/html/index.html
Files: /usr/share/doc/ncrack/html/*.html
